@@include('libs/jquery-3.6.0.min.js', {})
@@include('libs/jquery.fancybox.min.js', {})
@@include('libs/jquery.maskedinput.min.js', {})
@@include('libs/bootstrap.bundle.min.js', {})
@@include('libs/slick.min.js', {})